// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/v1/rexec.proto

package rexecv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Argv           []string               `protobuf:"bytes,1,rep,name=argv,proto3" json:"argv,omitempty"`
	Env            map[string]string      `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Cwd            string                 `protobuf:"bytes,3,opt,name=cwd,proto3" json:"cwd,omitempty"`
	TimeoutSeconds uint32                 `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_proto_v1_rexec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_rexec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_rexec_proto_rawDescGZIP(), []int{0}
}

func (x *RunRequest) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *RunRequest) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *RunRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *RunRequest) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        []byte                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        []byte                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_proto_v1_rexec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_rexec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_rexec_proto_rawDescGZIP(), []int{1}
}

func (x *RunResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *RunResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *RunResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *RunResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_v1_rexec_proto protoreflect.FileDescriptor

const file_proto_v1_rexec_proto_rawDesc = "" +
	"\n" +
	"\x14proto/v1/rexec.proto\x12\brexec.v1\"\xfd\x01\n" +
	"\n" +
	"RunRequest\x12\x12\n" +
	"\x04argv\x18\x01 \x03(\tR\x04argv\x12/\n" +
	"\x03env\x18\x02 \x03(\v2\x1d.rexec.v1.RunRequest.EnvEntryR\x03env\x12\x10\n" +
	"\x03cwd\x18\x03 \x01(\tR\x03cwd\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\rR\x0etimeoutSeconds\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x05\x10\x14R\x05stdinR\rallowlist_tagR\tclient_idR\x10signal_on_cancel\"\xad\x01\n" +
	"\vRunResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\fR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\fR\x06stderr\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05errorJ\x04\b\x05\x10\x14R\x06signalR\fstream_chunkR\x06rusageR\vduration_msR\n" +
	"started_at2@\n" +
	"\n" +
	"RemoteExec\x122\n" +
	"\x03Run\x12\x14.rexec.v1.RunRequest\x1a\x15.rexec.v1.RunResponseB1Z/github.com/Mouriya-Emma/rexecd/proto/v1;rexecv1b\x06proto3"

var (
	file_proto_v1_rexec_proto_rawDescOnce sync.Once
	file_proto_v1_rexec_proto_rawDescData []byte
)

func file_proto_v1_rexec_proto_rawDescGZIP() []byte {
	file_proto_v1_rexec_proto_rawDescOnce.Do(func() {
		file_proto_v1_rexec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_rexec_proto_rawDesc), len(file_proto_v1_rexec_proto_rawDesc)))
	})
	return file_proto_v1_rexec_proto_rawDescData
}

var file_proto_v1_rexec_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_v1_rexec_proto_goTypes = []any{
	(*RunRequest)(nil),  // 0: rexec.v1.RunRequest
	(*RunResponse)(nil), // 1: rexec.v1.RunResponse
	nil,                 // 2: rexec.v1.RunRequest.EnvEntry
}
var file_proto_v1_rexec_proto_depIdxs = []int32{
	2, // 0: rexec.v1.RunRequest.env:type_name -> rexec.v1.RunRequest.EnvEntry
	0, // 1: rexec.v1.RemoteExec.Run:input_type -> rexec.v1.RunRequest
	1, // 2: rexec.v1.RemoteExec.Run:output_type -> rexec.v1.RunResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_v1_rexec_proto_init() }
func file_proto_v1_rexec_proto_init() {
	if File_proto_v1_rexec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_rexec_proto_rawDesc), len(file_proto_v1_rexec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_rexec_proto_goTypes,
		DependencyIndexes: file_proto_v1_rexec_proto_depIdxs,
		MessageInfos:      file_proto_v1_rexec_proto_msgTypes,
	}.Build()
	File_proto_v1_rexec_proto = out.File
	file_proto_v1_rexec_proto_goTypes = nil
	file_proto_v1_rexec_proto_depIdxs = nil
}
