// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/v1/rexec.proto

package rexecv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RemoteExec_Run_FullMethodName = "/rexec.v1.RemoteExec/Run"
)

// RemoteExecClient is the client API for RemoteExec service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RemoteExec v1: minimal unary execute. Streaming / mTLS / allowlist are NOT
// implemented in v1, but their wire positions are reserved below.
type RemoteExecClient interface {
	Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error)
}

type remoteExecClient struct {
	cc grpc.ClientConnInterface
}

func NewRemoteExecClient(cc grpc.ClientConnInterface) RemoteExecClient {
	return &remoteExecClient{cc}
}

func (c *remoteExecClient) Run(ctx context.Context, in *RunRequest, opts ...grpc.CallOption) (*RunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunResponse)
	err := c.cc.Invoke(ctx, RemoteExec_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoteExecServer is the server API for RemoteExec service.
// All implementations must embed UnimplementedRemoteExecServer
// for forward compatibility.
//
// RemoteExec v1: minimal unary execute. Streaming / mTLS / allowlist are NOT
// implemented in v1, but their wire positions are reserved below.
type RemoteExecServer interface {
	Run(context.Context, *RunRequest) (*RunResponse, error)
	mustEmbedUnimplementedRemoteExecServer()
}

// UnimplementedRemoteExecServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRemoteExecServer struct{}

func (UnimplementedRemoteExecServer) Run(context.Context, *RunRequest) (*RunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedRemoteExecServer) mustEmbedUnimplementedRemoteExecServer() {}
func (UnimplementedRemoteExecServer) testEmbeddedByValue()                    {}

// UnsafeRemoteExecServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RemoteExecServer will
// result in compilation errors.
type UnsafeRemoteExecServer interface {
	mustEmbedUnimplementedRemoteExecServer()
}

func RegisterRemoteExecServer(s grpc.ServiceRegistrar, srv RemoteExecServer) {
	// If the following call panics, it indicates UnimplementedRemoteExecServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RemoteExec_ServiceDesc, srv)
}

func _RemoteExec_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteExecServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RemoteExec_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteExecServer).Run(ctx, req.(*RunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RemoteExec_ServiceDesc is the grpc.ServiceDesc for RemoteExec service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RemoteExec_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rexec.v1.RemoteExec",
	HandlerType: (*RemoteExecServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _RemoteExec_Run_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/rexec.proto",
}
